/// Flutter icons CubaIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CubaIcon
///      fonts:
///       - asset: fonts/CubaIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CubaIcon {
  CubaIcon._();

  static const _kFontFam = 'CubaIcon';
  static const _kFontPkg = null;

  static const IconData cuba =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
